# According to
# https://docs.travis-ci.com/user/languages/minimal-and-generic/#generic, the
# generic language includes Go.
language: generic
os: osx
compiler: clang

addons:
  apt:
    packages:
      - python3-pip

install:
  - pip install pre-commit

cache:
  directories:
    # https://pre-commit.com/#travis-ci-example 
    - $HOME/.cache/pre-commit
branches:
  only: 
    - master

before_install:
  - brew update
  - brew install wget

script:
  - set -e
  - (cd cgotorch; make)
  - pre-commit -a
  - go run 01-backward.go
